#!/usr/bin/env bash
# Write a Bash script that:
# Creates the file /var/run/myscript.pid containing its PID

GbasGboas() {
	rm /var/run/myscript.pid
	exit 0
}

trap "echo 'I hate the kill command' && GbasGboas" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "GbasGboas" SIGQUIT
echo '$$' > /var/run/myscript.pid
while true
do
  echo "To infinity and beyond"
  sleep 2
done
